spring.application.name=spring-data-jpa-examples

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5332/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.examples.spring_jpa.examples.QueryLimitInspector

spring.jpa.open-in-view=false

